# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/diy-page-cache-AEKDA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/diy-page-cache-AEKDA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/diy-page-cache-AEKDA/CMakeFiles /workspaces/diy-page-cache-AEKDA//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/diy-page-cache-AEKDA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cachelib

# Build rule for target.
cachelib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cachelib
.PHONY : cachelib

# fast build rule for target.
cachelib/fast:
	$(MAKE) $(MAKESILENT) -f cache_lib/CMakeFiles/cachelib.dir/build.make cache_lib/CMakeFiles/cachelib.dir/build
.PHONY : cachelib/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/src/CMakeFiles/benchmark.dir/build.make _deps/google_benchmark-build/src/CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

#=============================================================================
# Target rules for targets named benchmark_main

# Build rule for target.
benchmark_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_main
.PHONY : benchmark_main

# fast build rule for target.
benchmark_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/src/CMakeFiles/benchmark_main.dir/build.make _deps/google_benchmark-build/src/CMakeFiles/benchmark_main.dir/build
.PHONY : benchmark_main/fast

#=============================================================================
# Target rules for targets named output_test_helper

# Build rule for target.
output_test_helper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 output_test_helper
.PHONY : output_test_helper

# fast build rule for target.
output_test_helper/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/output_test_helper.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/output_test_helper.dir/build
.PHONY : output_test_helper/fast

#=============================================================================
# Target rules for targets named benchmark_test

# Build rule for target.
benchmark_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_test
.PHONY : benchmark_test

# fast build rule for target.
benchmark_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/benchmark_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/benchmark_test.dir/build
.PHONY : benchmark_test/fast

#=============================================================================
# Target rules for targets named spec_arg_test

# Build rule for target.
spec_arg_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spec_arg_test
.PHONY : spec_arg_test

# fast build rule for target.
spec_arg_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/spec_arg_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/spec_arg_test.dir/build
.PHONY : spec_arg_test/fast

#=============================================================================
# Target rules for targets named spec_arg_verbosity_test

# Build rule for target.
spec_arg_verbosity_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spec_arg_verbosity_test
.PHONY : spec_arg_verbosity_test

# fast build rule for target.
spec_arg_verbosity_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/spec_arg_verbosity_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/spec_arg_verbosity_test.dir/build
.PHONY : spec_arg_verbosity_test/fast

#=============================================================================
# Target rules for targets named benchmark_setup_teardown_test

# Build rule for target.
benchmark_setup_teardown_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_setup_teardown_test
.PHONY : benchmark_setup_teardown_test

# fast build rule for target.
benchmark_setup_teardown_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/benchmark_setup_teardown_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/benchmark_setup_teardown_test.dir/build
.PHONY : benchmark_setup_teardown_test/fast

#=============================================================================
# Target rules for targets named filter_test

# Build rule for target.
filter_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 filter_test
.PHONY : filter_test

# fast build rule for target.
filter_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/filter_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/filter_test.dir/build
.PHONY : filter_test/fast

#=============================================================================
# Target rules for targets named benchmark_min_time_flag_time_test

# Build rule for target.
benchmark_min_time_flag_time_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_min_time_flag_time_test
.PHONY : benchmark_min_time_flag_time_test

# fast build rule for target.
benchmark_min_time_flag_time_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/benchmark_min_time_flag_time_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/benchmark_min_time_flag_time_test.dir/build
.PHONY : benchmark_min_time_flag_time_test/fast

#=============================================================================
# Target rules for targets named benchmark_min_time_flag_iters_test

# Build rule for target.
benchmark_min_time_flag_iters_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_min_time_flag_iters_test
.PHONY : benchmark_min_time_flag_iters_test

# fast build rule for target.
benchmark_min_time_flag_iters_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/benchmark_min_time_flag_iters_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/benchmark_min_time_flag_iters_test.dir/build
.PHONY : benchmark_min_time_flag_iters_test/fast

#=============================================================================
# Target rules for targets named options_test

# Build rule for target.
options_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 options_test
.PHONY : options_test

# fast build rule for target.
options_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/options_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/options_test.dir/build
.PHONY : options_test/fast

#=============================================================================
# Target rules for targets named basic_test

# Build rule for target.
basic_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 basic_test
.PHONY : basic_test

# fast build rule for target.
basic_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/basic_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/basic_test.dir/build
.PHONY : basic_test/fast

#=============================================================================
# Target rules for targets named repetitions_test

# Build rule for target.
repetitions_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 repetitions_test
.PHONY : repetitions_test

# fast build rule for target.
repetitions_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/repetitions_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/repetitions_test.dir/build
.PHONY : repetitions_test/fast

#=============================================================================
# Target rules for targets named diagnostics_test

# Build rule for target.
diagnostics_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 diagnostics_test
.PHONY : diagnostics_test

# fast build rule for target.
diagnostics_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/diagnostics_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/diagnostics_test.dir/build
.PHONY : diagnostics_test/fast

#=============================================================================
# Target rules for targets named skip_with_error_test

# Build rule for target.
skip_with_error_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 skip_with_error_test
.PHONY : skip_with_error_test

# fast build rule for target.
skip_with_error_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/skip_with_error_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/skip_with_error_test.dir/build
.PHONY : skip_with_error_test/fast

#=============================================================================
# Target rules for targets named donotoptimize_test

# Build rule for target.
donotoptimize_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 donotoptimize_test
.PHONY : donotoptimize_test

# fast build rule for target.
donotoptimize_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/donotoptimize_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/donotoptimize_test.dir/build
.PHONY : donotoptimize_test/fast

#=============================================================================
# Target rules for targets named fixture_test

# Build rule for target.
fixture_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fixture_test
.PHONY : fixture_test

# fast build rule for target.
fixture_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/fixture_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/fixture_test.dir/build
.PHONY : fixture_test/fast

#=============================================================================
# Target rules for targets named register_benchmark_test

# Build rule for target.
register_benchmark_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 register_benchmark_test
.PHONY : register_benchmark_test

# fast build rule for target.
register_benchmark_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/register_benchmark_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/register_benchmark_test.dir/build
.PHONY : register_benchmark_test/fast

#=============================================================================
# Target rules for targets named map_test

# Build rule for target.
map_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 map_test
.PHONY : map_test

# fast build rule for target.
map_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/map_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/map_test.dir/build
.PHONY : map_test/fast

#=============================================================================
# Target rules for targets named multiple_ranges_test

# Build rule for target.
multiple_ranges_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 multiple_ranges_test
.PHONY : multiple_ranges_test

# fast build rule for target.
multiple_ranges_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/multiple_ranges_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/multiple_ranges_test.dir/build
.PHONY : multiple_ranges_test/fast

#=============================================================================
# Target rules for targets named args_product_test

# Build rule for target.
args_product_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 args_product_test
.PHONY : args_product_test

# fast build rule for target.
args_product_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/args_product_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/args_product_test.dir/build
.PHONY : args_product_test/fast

#=============================================================================
# Target rules for targets named link_main_test

# Build rule for target.
link_main_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 link_main_test
.PHONY : link_main_test

# fast build rule for target.
link_main_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/link_main_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/link_main_test.dir/build
.PHONY : link_main_test/fast

#=============================================================================
# Target rules for targets named reporter_output_test

# Build rule for target.
reporter_output_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reporter_output_test
.PHONY : reporter_output_test

# fast build rule for target.
reporter_output_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/reporter_output_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/reporter_output_test.dir/build
.PHONY : reporter_output_test/fast

#=============================================================================
# Target rules for targets named templated_fixture_test

# Build rule for target.
templated_fixture_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 templated_fixture_test
.PHONY : templated_fixture_test

# fast build rule for target.
templated_fixture_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/templated_fixture_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/templated_fixture_test.dir/build
.PHONY : templated_fixture_test/fast

#=============================================================================
# Target rules for targets named user_counters_test

# Build rule for target.
user_counters_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 user_counters_test
.PHONY : user_counters_test

# fast build rule for target.
user_counters_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/user_counters_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/user_counters_test.dir/build
.PHONY : user_counters_test/fast

#=============================================================================
# Target rules for targets named perf_counters_test

# Build rule for target.
perf_counters_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 perf_counters_test
.PHONY : perf_counters_test

# fast build rule for target.
perf_counters_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/perf_counters_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/perf_counters_test.dir/build
.PHONY : perf_counters_test/fast

#=============================================================================
# Target rules for targets named internal_threading_test

# Build rule for target.
internal_threading_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 internal_threading_test
.PHONY : internal_threading_test

# fast build rule for target.
internal_threading_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/internal_threading_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/internal_threading_test.dir/build
.PHONY : internal_threading_test/fast

#=============================================================================
# Target rules for targets named report_aggregates_only_test

# Build rule for target.
report_aggregates_only_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 report_aggregates_only_test
.PHONY : report_aggregates_only_test

# fast build rule for target.
report_aggregates_only_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/report_aggregates_only_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/report_aggregates_only_test.dir/build
.PHONY : report_aggregates_only_test/fast

#=============================================================================
# Target rules for targets named display_aggregates_only_test

# Build rule for target.
display_aggregates_only_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 display_aggregates_only_test
.PHONY : display_aggregates_only_test

# fast build rule for target.
display_aggregates_only_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/display_aggregates_only_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/display_aggregates_only_test.dir/build
.PHONY : display_aggregates_only_test/fast

#=============================================================================
# Target rules for targets named user_counters_tabular_test

# Build rule for target.
user_counters_tabular_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 user_counters_tabular_test
.PHONY : user_counters_tabular_test

# fast build rule for target.
user_counters_tabular_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/user_counters_tabular_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/user_counters_tabular_test.dir/build
.PHONY : user_counters_tabular_test/fast

#=============================================================================
# Target rules for targets named user_counters_thousands_test

# Build rule for target.
user_counters_thousands_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 user_counters_thousands_test
.PHONY : user_counters_thousands_test

# fast build rule for target.
user_counters_thousands_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/user_counters_thousands_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/user_counters_thousands_test.dir/build
.PHONY : user_counters_thousands_test/fast

#=============================================================================
# Target rules for targets named memory_manager_test

# Build rule for target.
memory_manager_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memory_manager_test
.PHONY : memory_manager_test

# fast build rule for target.
memory_manager_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/memory_manager_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/memory_manager_test.dir/build
.PHONY : memory_manager_test/fast

#=============================================================================
# Target rules for targets named profiler_manager_test

# Build rule for target.
profiler_manager_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 profiler_manager_test
.PHONY : profiler_manager_test

# fast build rule for target.
profiler_manager_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/profiler_manager_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/profiler_manager_test.dir/build
.PHONY : profiler_manager_test/fast

#=============================================================================
# Target rules for targets named cxx03_test

# Build rule for target.
cxx03_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cxx03_test
.PHONY : cxx03_test

# fast build rule for target.
cxx03_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/cxx03_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/cxx03_test.dir/build
.PHONY : cxx03_test/fast

#=============================================================================
# Target rules for targets named complexity_test

# Build rule for target.
complexity_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 complexity_test
.PHONY : complexity_test

# fast build rule for target.
complexity_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/google_benchmark-build/test/CMakeFiles/complexity_test.dir/build.make _deps/google_benchmark-build/test/CMakeFiles/complexity_test.dir/build
.PHONY : complexity_test/fast

#=============================================================================
# Target rules for targets named ItmoShell-bench-bin-search

# Build rule for target.
ItmoShell-bench-bin-search: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ItmoShell-bench-bin-search
.PHONY : ItmoShell-bench-bin-search

# fast build rule for target.
ItmoShell-bench-bin-search/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/ItmoShell-bench-bin-search.dir/build.make benchmark/CMakeFiles/ItmoShell-bench-bin-search.dir/build
.PHONY : ItmoShell-bench-bin-search/fast

#=============================================================================
# Target rules for targets named ItmoShell-bench-bin-search-std

# Build rule for target.
ItmoShell-bench-bin-search-std: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ItmoShell-bench-bin-search-std
.PHONY : ItmoShell-bench-bin-search-std

# fast build rule for target.
ItmoShell-bench-bin-search-std/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/ItmoShell-bench-bin-search-std.dir/build.make benchmark/CMakeFiles/ItmoShell-bench-bin-search-std.dir/build
.PHONY : ItmoShell-bench-bin-search-std/fast

#=============================================================================
# Target rules for targets named ItmoShell-bench-bin-search-multi-thread

# Build rule for target.
ItmoShell-bench-bin-search-multi-thread: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ItmoShell-bench-bin-search-multi-thread
.PHONY : ItmoShell-bench-bin-search-multi-thread

# fast build rule for target.
ItmoShell-bench-bin-search-multi-thread/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/ItmoShell-bench-bin-search-multi-thread.dir/build.make benchmark/CMakeFiles/ItmoShell-bench-bin-search-multi-thread.dir/build
.PHONY : ItmoShell-bench-bin-search-multi-thread/fast

#=============================================================================
# Target rules for targets named ItmoShell-bench-ema-search-str

# Build rule for target.
ItmoShell-bench-ema-search-str: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ItmoShell-bench-ema-search-str
.PHONY : ItmoShell-bench-ema-search-str

# fast build rule for target.
ItmoShell-bench-ema-search-str/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/ItmoShell-bench-ema-search-str.dir/build.make benchmark/CMakeFiles/ItmoShell-bench-ema-search-str.dir/build
.PHONY : ItmoShell-bench-ema-search-str/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ItmoShell-bench-bin-search"
	@echo "... ItmoShell-bench-bin-search-multi-thread"
	@echo "... ItmoShell-bench-bin-search-std"
	@echo "... ItmoShell-bench-ema-search-str"
	@echo "... args_product_test"
	@echo "... basic_test"
	@echo "... benchmark"
	@echo "... benchmark_main"
	@echo "... benchmark_min_time_flag_iters_test"
	@echo "... benchmark_min_time_flag_time_test"
	@echo "... benchmark_setup_teardown_test"
	@echo "... benchmark_test"
	@echo "... cachelib"
	@echo "... complexity_test"
	@echo "... cxx03_test"
	@echo "... diagnostics_test"
	@echo "... display_aggregates_only_test"
	@echo "... donotoptimize_test"
	@echo "... filter_test"
	@echo "... fixture_test"
	@echo "... internal_threading_test"
	@echo "... link_main_test"
	@echo "... map_test"
	@echo "... memory_manager_test"
	@echo "... multiple_ranges_test"
	@echo "... options_test"
	@echo "... output_test_helper"
	@echo "... perf_counters_test"
	@echo "... profiler_manager_test"
	@echo "... register_benchmark_test"
	@echo "... repetitions_test"
	@echo "... report_aggregates_only_test"
	@echo "... reporter_output_test"
	@echo "... skip_with_error_test"
	@echo "... spec_arg_test"
	@echo "... spec_arg_verbosity_test"
	@echo "... templated_fixture_test"
	@echo "... user_counters_tabular_test"
	@echo "... user_counters_test"
	@echo "... user_counters_thousands_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

